resources:
  - name: concourse-practice-git
    type: git
    source:
      uri: https://github.com/seiyab/concourse-practice.git
      branch: master

jobs:
  - name: concourse-practice
    public: true
    plan:
      - get: concourse-practice-git
        trigger: true
      - task: hello-world
        file: concourse-practice-git/ci/hello-world.yml
      - task: mvn
        file: concourse-practice-git/ci/mvn.yml
